version: '3.4'
services:
  database:
    container_name: database
    image: mariadb:10.7.1
    restart: always
    volumes:
      - type: bind
        source: ./.database
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ridara
    ports:
      - "33306:3306"
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - database
    ports:
      - "3000:3000"
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - api
    ports:
      - "3010:3010"
      - "24678:24678"
